import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Product360View from '../components/Product360View';
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>My Next.js App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
       
      </Head>

      <main className={styles.main}>
        <h1>Product 360 View</h1>
        <Product360View />
      </main>
    </div>
  );
}
